# Generated by Django 3.2 on 2021-05-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
